USE [RCS_SqlDw]
GO
CREATE TABLE [hospitality_DW].[BREIT_RPT]
(
	[PropertyName] [varchar](100) NULL,
	[PropertyId_AK] [varchar](100) NOT NULL,
	[STRID] [int] NOT NULL,
	[AssetManager] [varchar](100) NULL,
	[Market] [varchar](50) NULL,
	[Region] [varchar](50) NULL,
	[Affiliation] [varchar](50) NULL,
	[ManagementCompany] [varchar](100) NULL,
	[WeeklyComparableStatus] [varchar](30) NULL,
	[MonthlyComparableStatus] [varchar](30) NULL,
	[Fund] [varchar](100) NULL,
	[Portfolio] [varchar](100) NULL,
	[Investment] [varchar](100) NULL,
	[RoomRange] [varchar](100) NULL,
	[NumberOfKeys] [varchar](30) NULL,
	[AssetCategory] [varchar](100) NULL,
	[AssetClass] [varchar](50) NULL,
	[Flag] [varchar](100) NULL,
	[Brand] [varchar](100) NULL,
	[Scale] [varchar](100) NULL,
	[MSA] [varchar](50) NULL,
	[LocationCategory] [varchar](100) NULL,
	[PropertyStatus] [varchar](30) NULL,
	[AddressLine1] [varchar](100) NULL,
	[AddressLine2] [varchar](100) NULL,
	[AddressLine3] [varchar](100) NULL,
	[AddressLine4] [varchar](100) NULL,
	[City] [varchar](100) NULL,
	[State] [varchar](30) NULL,
	[PostalCode] [varchar](30) NULL,
	[AssetID] [varchar](50) NULL,
	[InnCode] [varchar](50) NULL,
	[Region2] [varchar](50) NULL,
	[ConsolidatedStatus] [nvarchar](50) NULL,
	[YearMonth] [int] NULL,
	[Year] [smallint] NULL,
	[Month] [tinyint] NULL,
	[Quarter] [tinyint] NULL,
	[STR_Monthly_AvailableRooms] [int] NULL,
	[STR_Monthly_RoomsSold] [int] NULL,
	[STR_Monthly_RoomRevenue] [numeric](12, 2) NULL,
	[STR_Monthly_GroupPaidOccupiedRooms] [int] NULL,
	[STR_L3M_AvailableRooms] [int] NULL,
	[STR_L3M_RoomsSold] [int] NULL,
	[STR_L3M_RoomRevenue] [numeric](12, 2) NULL,
	[STR_L3M_GroupPaidOccupiedRooms] [int] NULL,
	[STR_Monthly_CompSetAvailableRooms] [varchar](30) NULL,
	[STR_Monthly_CompSetRoomsSold] [int] NULL,
	[STR_Monthly_CompSetRoomRevenue] [numeric](12, 2) NULL,
	[STR_Monthly_Occupancy] [numeric](16, 6) NULL,
	[STR_Monthly_Occupancy_Index] [numeric](16, 6) NULL,
	[STR_Monthly_ADR] [numeric](12, 2) NULL,
	[STR_Monthly_ADR_Index] [numeric](16, 6) NULL,
	[STR_Monthly_RevPAR] [numeric](12, 2) NULL,
	[STR_Monthly_RevPAR_Index] [numeric](16, 6) NULL,
	[STR_Monthly_Transient_Room_Revenue] [numeric](12, 2) NULL,
	[STR_Monthly_Transient_Rooms_Sold] [int] NULL,
	[STR_Monthly_Contract_Room_Revenue] [numeric](12, 2) NULL,
	[STR_Monthly_Contract_Rooms_Sold] [int] NULL,
	[STR_Monthly_Group_Room_Revenue] [numeric](12, 2) NULL,
	[STR_Monthly_Group_Rooms_Sold] [int] NULL,
	[STR_L3M_Monthly_CompSetAvailableRooms] [varchar](30) NULL,
	[STR_L3M_Monthly_CompSetRoomsSold] [int] NULL,
	[STR_L3M_Monthly_CompSetRoomRevenue] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_Occupancy] [numeric](16, 6) NULL,
	[STR_L3M_Monthly_Occupancy_Index] [numeric](16, 6) NULL,
	[STR_L3M_Monthly_ADR] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_ADR_Index] [numeric](16, 6) NULL,
	[STR_L3M_Monthly_RevPAR] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_RevPAR_Index] [numeric](16, 6) NULL,
	[STR_L3M_Monthly_Transient_Room_Revenue] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_Transient_Rooms_Sold] [int] NULL,
	[STR_L3M_Monthly_Contract_Room_Revenue] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_Contract_Rooms_Sold] [int] NULL,
	[STR_L3M_Monthly_Group_Room_Revenue] [numeric](12, 2) NULL,
	[STR_L3M_Monthly_Group_Rooms_Sold] [int] NULL,
	[WorkdayAvailableRooms] [decimal](38, 2) NULL,
	[WorkdayOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayRoomRevenue] [decimal](38, 2) NULL,
	[WorkdayGroupPaidOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayRetailPaidOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayNegotiatedPaidOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayLeasePaidOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayOtherPaidOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayTotalOccupiedRooms] [decimal](38, 2) NULL,
	[WorkdayOccupancy] [decimal](38, 6) NULL,
	[L3M_WorkdayAvailableRooms] [decimal](38, 2) NULL,
	[L3M_WorkdayRoomsSold] [decimal](38, 2) NULL,
	[L3M_WorkdayRoomRevenue] [decimal](38, 2) NULL,
	[L3M_WorkdayOccupancy] [decimal](38, 6) NULL,
	[L3M_WorkdayADR] [decimal](38, 6) NULL,
	[L3M_WorkdayRevPAR] [decimal](38, 6) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO


