CREATE VIEW [RCS_DW].[v_ReportLineCalcGroupMapping]
AS
SELECT
    [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
UNION ALL
SELECT
    [CalcReportLineId] AS [ReportLineId]
  , [map].[ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [calcmap].[signFactor]
  , [calcmap].[constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping] AS [base]
INNER JOIN [RCS_DW].[ReportLineCalcBusinessMapping] AS [calcmap]
INNER JOIN [RCS_DW].[ReportLineMapping] AS [map] ON [map].[ReportLineId] = [calcmap].[CalcReportLineId] ON [base].[ReportLineId] = [calcmap].[ReportLineId]
UNION ALL
SELECT
    'L204' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L206' AND [CostCenterDesc] NOT IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L205' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L206' AND [CostCenterDesc] IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L2033' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L206' AND [LedgerAccountName] NOT IN ('BRH | 400050 | Food Revenue', 'BRH | 400060 | Beverage Revenue')
UNION ALL
SELECT
    'L310' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L3090' AND [CostCenterDesc] NOT IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L311' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L3090' AND [CostCenterDesc] IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L312' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L3110' AND [CostCenterDesc] NOT IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L313' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L3110' AND [CostCenterDesc] IN ('Catering (Local/Social related)', 'Banquets (Group Rooms Related)')
UNION ALL
SELECT
    'L401' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L402'
  AND [LedgerAccountName] NOT IN ('BRH | 214010 | Accrued Payroll', 'BRH | 500250 | Property Payroll Taxes and related expenses'
                                , 'BRH | 500220 | Property Payroll - Overtime Pay (by Skill set)', 'BRH | 500240 | Property Payroll - Benefits'
                                , 'BRH | 500230 | Property Payroll - Other Pay', 'BRH | 211050 | Unclaimed Wages Payroll'
                                , 'BRH | 214020 | Accrued Payroll Taxes', 'BRH | 500210 | Property Payroll - Regular Pay (by Skill set)')
UNION ALL
SELECT
    'L407' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L408'
  AND [LedgerAccountName] NOT IN ('BRH | 214010 | Accrued Payroll', 'BRH | 500250 | Property Payroll Taxes and related expenses'
                                , 'BRH | 500220 | Property Payroll - Overtime Pay (by Skill set)', 'BRH | 500240 | Property Payroll - Benefits'
                                , 'BRH | 500230 | Property Payroll - Other Pay', 'BRH | 211050 | Unclaimed Wages Payroll'
                                , 'BRH | 214020 | Accrued Payroll Taxes', 'BRH | 500210 | Property Payroll - Regular Pay (by Skill set)')
UNION ALL
SELECT
    'L420' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L421'
  AND [LedgerAccountName] NOT IN ('BRH | 214010 | Accrued Payroll', 'BRH | 500250 | Property Payroll Taxes and related expenses'
                                , 'BRH | 500220 | Property Payroll - Overtime Pay (by Skill set)', 'BRH | 500240 | Property Payroll - Benefits'
                                , 'BRH | 500230 | Property Payroll - Other Pay', 'BRH | 211050 | Unclaimed Wages Payroll'
                                , 'BRH | 214020 | Accrued Payroll Taxes', 'BRH | 500210 | Property Payroll - Regular Pay (by Skill set)')
UNION ALL
SELECT
    'L412' AS [ReportLineId]
  , 'S&M (less Marketing Fees/Frequent Guest Program/Web Site)' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L418'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] IN ('L414', 'L415', 'L416')) AS [datL412]
UNION ALL
SELECT
    'L411' AS [ReportLineId]
  , 'S&M Other Expense' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L418'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] IN ('L414', 'L415', 'L416')) AS [datL411]
WHERE [LedgerAccountName] NOT IN ('BRH | 214010 | Accrued Payroll', 'BRH | 500250 | Property Payroll Taxes and related expenses'
                                , 'BRH | 500220 | Property Payroll - Overtime Pay (by Skill set)', 'BRH | 500240 | Property Payroll - Benefits'
                                , 'BRH | 500230 | Property Payroll - Other Pay', 'BRH | 211050 | Unclaimed Wages Payroll'
                                , 'BRH | 214020 | Accrued Payroll Taxes', 'BRH | 500210 | Property Payroll - Regular Pay (by Skill set)')
UNION ALL
SELECT
    'L304' AS [ReportLineId]
  , 'Rooms Other Exp (excl. TA)' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L305' AND [CategoryDesc] NOT LIKE 'RC%'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] IN ('L300', 'L301')) AS [datL304]
UNION ALL
SELECT
    'L314' AS [ReportLineId]
  , [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L315'
  AND [LedgerAccountName] IN ('BRH | 500260 | Other Expense', 'BRH | 500270 | Contract Expense', 'BRH | 500280 | Complimentary Expense'
                              , 'BRH | 500290 | Commissions Expense')
UNION ALL
SELECT
    'L611' AS [ReportLineId]
  , 'Undistributed (less CC/Marketing Fees/Frequent Guest Program/Web Site)' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] IN ('L423', 'L421', 'L408', 'L402', 'L4180')
UNION ALL
SELECT
    'L611' AS [ReportLineId]
  , 'Undistributed (less CC/Marketing Fees/Frequent Guest Program/Web Site)' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L418'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] IN ('L414', 'L415', 'L416')) AS [dataL412]
UNION ALL
SELECT
    'L1001' AS [ReportLineId]
  , 'Other Occupied Rooms' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L1002'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L100' ) AS [datL1001]
UNION ALL
SELECT
    'L2030' AS [ReportLineId]
  , 'Non Group Room Revenue' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L203'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L201' ) AS [datL2030]
UNION ALL
SELECT
    'L3081' AS [ReportLineId]
  , 'Total Payroll - F&B Dept (Excl Service Chrgs)' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L308'
  AND [LedgerAccountName] IN ('BRH | 500210 | Property Payroll - Regular Pay (by Skill set)', 'BRH | 500220 | Property Payroll - Overtime Pay (by Skill set)')
  AND [CategoryDesc] NOT IN ('SC1690 | Service Charge Payroll')
UNION ALL
SELECT
    'L625' AS [ReportLineId]
  , 'F&B Other Operating Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
WHERE [ReportLineId] = 'L624'
  AND [LedgerAccountName] IN ('BRH | 500260 | Other Expense', 'BRH | 500270 | Contract Expense', 'BRH | 500280 | Complimentary Expense')
UNION ALL
SELECT
    'L309' AS [ReportLineId]
  , 'Cost of Sales' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L626'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM( SELECT
                [CostCenterDesc]
              , [CostCenter_SK]
              , [LedgerAccountName]
              , [LedgerAccount_SK]
              , [CategoryDesc]
              , [Category_SK]
              , [ReportLineGroupId]
              , [signFactor]
            FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
            WHERE [ReportLineId] = 'L308'
            UNION ALL
            SELECT
                [CostCenterDesc]
              , [CostCenter_SK]
              , [LedgerAccountName]
              , [LedgerAccount_SK]
              , [CategoryDesc]
              , [Category_SK]
              , [ReportLineGroupId]
              , [signFactor]
            FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
            WHERE [ReportLineId] = 'L624'
              AND [LedgerAccountName] IN ('BRH | 500260 | Other Expense', 'BRH | 500270 | Contract Expense', 'BRH | 500280 | Complimentary Expense'
                                          , 'BRH | 500290 | Commissions Expense')) AS [datL308plusL625] ) AS [datL309]
UNION ALL
SELECT
    'L3410' AS [ReportLineId]
  , 'Casino Profit' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L2120'
      UNION ALL
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L627' ) AS [datL3410]
UNION ALL
SELECT
    [LineItem].[ReportLineId]
  , [LineItem].[ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L2120'
      UNION ALL
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L627' ) AS [datL3410]
CROSS JOIN( SELECT [ReportLineId], [ReportLineItem] FROM [RCS_DW].[v_ReportLineMapping] WHERE [REportLineId] IN ('L529', 'L351', 'L500', 'L508', 'L517', 'L520'
                                                                                                                 , 'L617')) AS [LineItem]
UNION ALL
SELECT
    'L202' AS [ReportLineId]
  , 'Other Room Revenue' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L203'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] IN ('L121', 'L122', 'L201', 'L2010')) AS [L202]
UNION ALL
SELECT
    'L320' AS [ReportLineId]
  , 'Telecommunications Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L318'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6291' ) AS [datL320]
UNION ALL
SELECT
    'L324' AS [ReportLineId]
  , 'Retail Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L322'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6281' ) AS [datL324]
UNION ALL
SELECT
    'L328' AS [ReportLineId]
  , 'Spa Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L326'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6311' ) AS [datL328]
UNION ALL
SELECT
    'L332' AS [ReportLineId]
  , 'Membership Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L330'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6331' ) AS [datL332]
UNION ALL
SELECT
    'L336' AS [ReportLineId]
  , 'Recreation Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L334'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6321' ) AS [datL336]
UNION ALL
SELECT
    'L3410001' AS [ReportLineId]
  , 'Casino Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L34100'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6371' ) AS [datL3410001]
UNION ALL
SELECT
    'L34102' AS [ReportLineId]
  , 'Golf Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L34101'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6341' ) AS [datL34102]
UNION ALL
SELECT
    'L34112' AS [ReportLineId]
  , 'Tennis Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L34111'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L63472' ) AS [datL34112]
UNION ALL
SELECT
    'L341202' AS [ReportLineId]
  , 'Marina Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L341201'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6351' ) AS [datL341202]
UNION ALL
SELECT
    'L34142' AS [ReportLineId]
  , 'Business Center Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L34141'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L63482' ) AS [datL34142]
UNION ALL
SELECT
    'L341502' AS [ReportLineId]
  , 'Condo Rental Management Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L341501'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6361' ) AS [datL341502]
UNION ALL
SELECT
    'L354' AS [ReportLineId]
  , 'Administrative & General Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L353'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6381' ) AS [datL354]
UNION ALL
SELECT
    'L4092' AS [ReportLineId]
  , 'Sales & Marketing Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L4091'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6401' ) AS [datL4092]
UNION ALL
SELECT
    'L4183' AS [ReportLineId]
  , 'Repairs & Maintenance Other Expenses' AS [ReportLineItem]
  , [CostCenterDesc]
  , [CostCenter_SK]
  , [LedgerAccountName]
  , [LedgerAccount_SK]
  , [CategoryDesc]
  , [Category_SK]
  , [ReportLineGroupId]
  , [signFactor]
  , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
FROM( SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L4182'
      EXCEPT
      SELECT
          [CostCenterDesc]
        , [CostCenter_SK]
        , [LedgerAccountName]
        , [LedgerAccount_SK]
        , [CategoryDesc]
        , [Category_SK]
        , [ReportLineGroupId]
        , [signFactor]
        , CAST(1 AS DECIMAL(10, 5)) AS [constFactor]
      FROM [RCS_DW].[v_ReportLineBaseGroupMapping]
      WHERE [ReportLineId] = 'L6411' ) AS [datL4183] ;
GO
